services:
  frontend:
    build: https://github.com/radioegor146/mail-re146-dev.git#:frontend
    restart: always
    networks:
      - mail-re146-dev
  backend:
    build: https://github.com/radioegor146/mail-re146-dev.git#:backend
    restart: always
    environment:
      STORAGE_PATH: /storage
      RETENTION_TIME: 60000
      DATABASE_URL: postgres://mail:mail@postgres:5432/mail
    volumes:
      - ./storage:/storage
    networks:
      - mail-re146-dev
      - mail-re146-dev-database
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mail
      POSTGRES_USER: mail
      POSTGRES_PASSWORD: mail
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mail-re146-dev-database
  nginx:
    build: https://github.com/radioegor146/mail-re146-dev.git#:nginx
    restart: always
    volumes:
      - ./storage:/storage
    networks:
      - mail-re146-dev
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail-re146-dev.entrypoints=web"
      - "traefik.http.routers.mail-re146-dev.rule=Host(`mail.re146.dev`)"
      - "traefik.http.services.mail-re146-dev-svc.loadbalancer.server.port=3000"
  smtp:
    build: https://github.com/radioegor146/mail-re146-dev.git#:smtp
    restart: always
    environment:
      TLS_KEY_PATH: /tls/server.key
      TLS_CERTIFICATE_PATH: /tls/server.crt
      STORAGE_PATH: /storage
      DATABASE_URL: postgres://mail:mail@postgres:5432/mail
    volumes:
      - ./storage:/storage
      - ./smtp-tls:/tls
    ports:
      - 0.0.0.0:25:25
      - 0.0.0.0:465:465
      - 0.0.0.0:587:587
    networks:
      - mail-re146-dev-database

networks:
  traefik:
    external: true
  mail-re146-dev:
  mail-re146-dev-database: